import { DEFAULT_EVALUATION_THRESHOLDS } from '@/lib/evaluation';
import type { ProjectData } from './types';

export const DEFAULT_PROJECT_DATA: ProjectData = {
  title: 'Untitled Project',
  concept: '',
  genre: '',
  tone: '',
  format: 'custom',
  customFormat: '',
  specialRequests: '',
  addVoiceover: false,
  product: '',
  targetAudience: '',
  mainMessage: '',
  callToAction: '',
  conceptOption: 'ai',
  aspectRatio: '16:9',
  videoStyle: 'cinematic',
  adBrief: {
    product: '',
    targetAudience: '',
    mainMessage: '',
    callToAction: '',
    adDuration: '30s',
    platform: 'all',
    brandGuidelines: '',
  },
  musicVideoData: {
    artistName: '',
    trackTitle: '',
    genre: '',
    lyrics: '',
    performanceRatio: 50,
  },
  infotainmentData: {
    topic: '',
    educationalGoals: [],
    targetDemographic: '',
    hostStyle: 'casual',
    segments: [],
    keyFacts: '',
    visualStyle: '',
  },
  shortFilmData: {
    genre: '',
    tone: '',
    duration: '',
    visualStyle: '',
  },
  voiceoverId: '',
  voiceoverName: '',
  voiceoverPreviewUrl: '',
  storylineTextModel: 'gmi/gemini-3.1-flash-lite',
  storylineTextSettings: {},
  baseImageModel: 'gmi/seedream-5.0-lite',
  baseVideoModel: 'gmi/ltx-fast-i2v',
  baseAudioModel: 'fal-ai/elevenlabs/tts/turbo-v2.5',
  evaluationMode: 'shadow',
  evaluationThresholds: DEFAULT_EVALUATION_THRESHOLDS,
  canonFacts: [],
  creativeConstraints: [],
};
